version: '3'
services:
  scan-bot:
    image: jonesabino/argyle:1.1
    working_dir: /usr/src/app
    command: >
      bash -c "poetry run python main.py"
    volumes:
      - type: bind
        source: $PWD/output
        target: /usr/src/app/output
